#!/usr/bin/env python

Import('env')
Import('env_modules')

env_fsctl = env_modules.Clone()
env_fsctl.Append(CPPPATH=['#modules/fs_control/'])

# Module files
env_fsctl.add_source_files(env.modules_sources, "*.cpp")

if (env["platform"] == 'windows'):
	env_fsctl.add_source_files(env.modules_sources, "platform/windows/*.cpp")
elif (env["platform"] == 'osx'):
	env_fsctl.add_source_files(env.modules_sources, "platform/macos/*.mm")
elif env["platform"] == 'x11':
	env_fsctl.add_source_files(env.modules_sources, "platform/linuxbsd/*.cpp")
